config/routes.rb
Rails.application.routes.draw do
  get '/', controller: 'bid_summary', action: :index

  resources :products
  resources :bidders
  resources :bids

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
end

app/models/bidder.rb
class Bidder < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bid_summary_controller.rb
class BidSummaryController < ApplicationController

  def index
    products = Product.all
    bidders = Bidder.all
    bids = Bid.all

    @bid_summary = BidSummary::IndexView.new(products, bidders, bids)
  end
end

app/controllers/bidders_controller.rb
class BiddersController < ApplicationController
  before_action :set_bidder, only: [:show, :edit, :update, :destroy]

  # GET /bidders
  # GET /bidders.json
  def index
    @bidders = Bidder.all
  end

  # GET /bidders/1
  # GET /bidders/1.json
  def show
  end

  # GET /bidders/new
  def new
    @bidder = Bidder.new
  end

  # GET /bidders/1/edit
  def edit
  end

  # POST /bidders
  # POST /bidders.json
  def create
    @bidder = Bidder.new(bidder_params)

    respond_to do |format|
      if @bidder.save
        format.html { redirect_to @bidder, notice: 'Bidder was successfully created.' }
        format.json { render :show, status: :created, location: @bidder }
      else
        format.html { render :new }
        format.json { render json: @bidder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bidders/1
  # PATCH/PUT /bidders/1.json
  def update
    respond_to do |format|
      if @bidder.update(bidder_params)
        format.html { redirect_to @bidder, notice: 'Bidder was successfully updated.' }
        format.json { render :show, status: :ok, location: @bidder }
      else
        format.html { render :edit }
        format.json { render json: @bidder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bidders/1
  # DELETE /bidders/1.json
  def destroy
    @bidder.destroy
    respond_to do |format|
      format.html { redirect_to bidders_url, notice: 'Bidder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bidder
      @bidder = Bidder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bidder_params
      params.require(:bidder).permit(:first_name, :last_name, :limit, :decimal, :active)
    end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]

  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = Bid.new(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:quantity, :bid_amount, :buid)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:publisher, :title, :reserve_price, :decimal, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bidders_helper.rb
module BiddersHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/bid_summary/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bid Summary</h1>

<p><%= "BID COUNT: #{@bid_summary.bids.count}" %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ProductID</th>
      <th>Title</th>
      <th>Quantity</th>
      <th>High Bid Amount</th>
      <th>Demand</th>
      <th>Reserve Met?</th>
    </tr>
  </thead>

  <tbody>
    <% @bid_summary.bid_rows.each do |row| %>
      <tr>
        <td><%= row.aucid %></td>
        <td><%= row.title %></td>
        <td><%= row.quantity %></td>
        <td><%= number_to_currency(row.high_bid) %></td>
        <td><%= row.demand %></td>
        <td><%= row.reserve_met %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bidders/_form.html.erb
<%= form_for(bidder) do |f| %>
  <% if bidder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bidder.errors.count, "error") %> prohibited this bidder from being saved:</h2>

      <ul>
      <% bidder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buid %>
    <%= f.text_field :buid %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :limit %>
    <%= f.text_field :limit %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bidders/edit.html.erb
<h1>Editing Bidder</h1>

<%= render 'form', bidder: @bidder %>

<%= link_to 'Show', @bidder %> |
<%= link_to 'Back', bidders_path %>

app/views/bidders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bidders</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>BUID</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Limit</th>
      <th>Active</th>
    </tr>
  </thead>

  <tbody>
    <% @bidders.each do |bidder| %>
      <tr>
        <td><%= bidder.id %></td>
        <td><%= bidder.buid %></td>
        <td><%= bidder.first_name %></td>
        <td><%= bidder.last_name %></td>
        <td><%= number_to_currency(bidder.limit) %></td>
        <td><%= bidder.active %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bidders/new.html.erb
<h1>New Bidder</h1>

<%= render 'form', bidder: @bidder %>

<%= link_to 'Back', bidders_path %>

app/views/bidders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @bidder.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @bidder.last_name %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @bidder.limit %>
</p>

<p>
  <strong>Decimal:</strong>
  <%= @bidder.decimal %>
</p>

<p>
  <strong>Active:</strong>
  <%= @bidder.active %>
</p>

<%= link_to 'Edit', edit_bidder_path(@bidder) %> |
<%= link_to 'Back', bidders_path %>

app/views/bids/_form.html.erb
<%= form_for(bid) do |f| %>
  <% if bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% bid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :bid_amount %>
    <%= f.text_field :bid_amount %>
  </div>

  <div class="field">
    <%= f.label :buid %>
    <%= f.text_field :buid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bids</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>ProductID</th>
      <th>Title</th>
      <th>Quantity</th>
      <th>Bid Amount</th>
      <th>BUID</th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.id %></td>
        <td><%= bid.puid %></td>
        <td><%= bid.title %></td>
        <td><%= bid.quantity %></td>
        <td><%= number_to_currency(bid.bid_amount) %></td>
        <td><%= bid.buid %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bids/new.html.erb
<h1>New Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>

app/views/layouts/SAMPLE_app.html.erb
<!DOCTYPE>
<html>
<head>
  <title>FlexBlogger</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/styles/solarized_dark.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js"></script>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <%= render "layouts/nav_bar" %>

  <div class=hero>
    <div class=hero-inner>
      <div class=hero-copy>
        <h1><%= "#{Rails.configuration.title}" %></h1>
        <p><%= "#{Rails.configuration.sub_title}" %></p>
      </div>
    </div>
  </div>
  <%= render "layouts/flashes" %>
  </header>

  <main>
  <%= yield %>
  </main>

  <%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/layouts/_nav_bar.erb
<nav class="navbar navbar-toggleable-md  navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">ComicUp</a>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" <%= link_to "Products", products_url %> <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" <%= link_to "Bidders", bidders_url %></a>
      <a class="nav-item nav-link" <%= link_to "Bids", bids_url %></a>
      <a class="nav-item nav-link" <%= link_to "Bid Summary", :controller => "bid_summary" %></a>
      <a class="nav-item nav-link disabled" href="#">Admin</a>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="nav-link">
  <%= link_to "Blog", root_path %>
</li>
<li class="nav-link">
  <%= link_to "About", about_index_path %>
</li>
<li class="nav-link">
  <%= link_to "Summary", summary_index_path %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BidderUp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <%= render "layouts/nav_bar" %>
      <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-3">ComicCon-Job</h1>
          <p class="lead">The premiere faux auction site for only the best of the best in comic nerdery.</p>
        </div>
      </div>
    </header>

    <div class="container">
      <div class="mt-3">
      </div>
      <p class="lead">
        <%= yield %>
      </p>
    </div>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :publisher %>
    <%= f.text_field :publisher %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :reserve_price %>
    <%= f.text_field :reserve_price %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>AUCID</th>
      <th>Publisher</th>
      <th>Title</th>
      <th>Quantity</th>
      <th>Reserve price</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.aucid %></td>
        <td><%= product.publisher %></td>
        <td><%= product.title %></td>
        <td><%= product.quantity %></td>
        <td><%= number_to_currency(product.reserve_price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Publisher:</strong>
  <%= @product.publisher %>
</p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Reserve price:</strong>
  <%= @product.reserve_price %>
</p>

<p>
  <strong>Decimal:</strong>
  <%= @product.decimal %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>